// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using data.Concrate;

#nullable disable

namespace data.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250324104605_Mig_2")]
    partial class Mig_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("entity.Concrate.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("entity.Concrate.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("entity.Concrate.ArastirmaProjesi", b =>
                {
                    b.Property<int>("ArastirmaProjesi_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArastirmaProjesi_Id"));

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<string>("KurumIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("No")
                        .HasColumnType("int");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Puan")
                        .HasColumnType("float");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("ArastirmaProjesi_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("ArastirmaProjesis");
                });

            modelBuilder.Entity("entity.Concrate.Atif", b =>
                {
                    b.Property<int>("Atif_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Atif_Id"));

                    b.Property<string>("AtifSayi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Puan")
                        .HasColumnType("float");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.HasKey("Atif_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("Atifs");
                });

            modelBuilder.Entity("entity.Concrate.Basvuru", b =>
                {
                    b.Property<int>("Basvuru_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Basvuru_Id"));

                    b.Property<int?>("Ilan_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<int>("Statu")
                        .HasColumnType("int");

                    b.HasKey("Basvuru_Id");

                    b.HasIndex("Ilan_Id");

                    b.HasIndex("Personel_Id");

                    b.ToTable("Basvurus");
                });

            modelBuilder.Entity("entity.Concrate.Belge", b =>
                {
                    b.Property<int>("Belge_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Belge_Id"));

                    b.Property<int>("Basvuru_Id")
                        .HasColumnType("int");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Belge_Id");

                    b.HasIndex("Basvuru_Id");

                    b.ToTable("Belges");
                });

            modelBuilder.Entity("entity.Concrate.BilimselToplanti", b =>
                {
                    b.Property<int>("BilimselToplanti_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BilimselToplanti_Id"));

                    b.Property<string>("BildiriIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<string>("KonferansIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<float>("Puan")
                        .HasColumnType("real");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<int>("SayfaSayi")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date");

                    b.Property<string>("YapildigiYer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YazarSayi")
                        .HasColumnType("int");

                    b.HasKey("BilimselToplanti_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("BilimselToplantis");
                });

            modelBuilder.Entity("entity.Concrate.Editorluk", b =>
                {
                    b.Property<int>("Editorluk_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Editorluk_Id"));

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Puan")
                        .HasColumnType("float");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Sayi")
                        .HasColumnType("int");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Editorluk_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("Editorluks");
                });

            modelBuilder.Entity("entity.Concrate.EoFaaliyetleri", b =>
                {
                    b.Property<int>("EoFaaliyetleri_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EoFaaliyetleri_Id"));

                    b.Property<string>("DersIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Donem")
                        .HasColumnType("int");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<string>("ProgramIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Puan")
                        .HasColumnType("float");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("EoFaaliyetleri_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("EoFaaliyetleris");
                });

            modelBuilder.Entity("entity.Concrate.Gorev", b =>
                {
                    b.Property<int>("Gorev_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Gorev_Id"));

                    b.Property<string>("Birim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<bool?>("Puan")
                        .HasColumnType("bit");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Gorev_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("Gorevs");
                });

            modelBuilder.Entity("entity.Concrate.Ilan", b =>
                {
                    b.Property<int>("Ilan_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ilan_Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Ilan_Id");

                    b.ToTable("Ilans");
                });

            modelBuilder.Entity("entity.Concrate.Katsayi", b =>
                {
                    b.Property<int>("Katsayi_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Katsayi_Id"));

                    b.Property<int>("CalisanSayi")
                        .HasColumnType("int");

                    b.Property<double>("Katsayisi")
                        .HasColumnType("float");

                    b.HasKey("Katsayi_Id");

                    b.ToTable("Katsayis");
                });

            modelBuilder.Entity("entity.Concrate.Kitap", b =>
                {
                    b.Property<int>("Kitap_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kitap_Id"));

                    b.Property<int?>("BaskiSayi")
                        .HasColumnType("int");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Puan")
                        .HasColumnType("float");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<string>("YayimYeri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yayinevi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YazarSayi")
                        .HasColumnType("int");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Kitap_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("Kitaps");
                });

            modelBuilder.Entity("entity.Concrate.Konservatuvar", b =>
                {
                    b.Property<int>("Konservatuvar_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Konservatuvar_Id"));

                    b.Property<string>("FaaliyetIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Puan")
                        .HasColumnType("float");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Konservatuvar_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("Konservatuvars");
                });

            modelBuilder.Entity("entity.Concrate.Makale", b =>
                {
                    b.Property<int>("Makale_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Makale_Id"));

                    b.Property<int>("BasimYili")
                        .HasColumnType("int");

                    b.Property<string>("CiltNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DergiIsim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<double>("Puan")
                        .HasColumnType("float");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<int>("SayfaSayi")
                        .HasColumnType("int");

                    b.Property<int>("YazarSayi")
                        .HasColumnType("int");

                    b.HasKey("Makale_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("Makales");
                });

            modelBuilder.Entity("entity.Concrate.Odul", b =>
                {
                    b.Property<int>("Odul_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Odul_Id"));

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<string>("KurumIsmi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Puan")
                        .HasColumnType("float");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Odul_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("Oduls");
                });

            modelBuilder.Entity("entity.Concrate.Patent", b =>
                {
                    b.Property<int>("Patent_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Patent_Id"));

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Puan")
                        .HasColumnType("float");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("Patent_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("Patents");
                });

            modelBuilder.Entity("entity.Concrate.Personel", b =>
                {
                    b.Property<int>("Personel_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Personel_Id"));

                    b.Property<string>("Eposta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyisim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TC")
                        .HasColumnType("int");

                    b.Property<int>("Telefon")
                        .HasColumnType("int");

                    b.Property<int>("Unvan_Id")
                        .HasColumnType("int");

                    b.HasKey("Personel_Id");

                    b.HasIndex("Unvan_Id");

                    b.ToTable("Personels");
                });

            modelBuilder.Entity("entity.Concrate.Personel_Role", b =>
                {
                    b.Property<int>("Personel_Role_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Personel_Role_Id"));

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<int>("Rol_Id")
                        .HasColumnType("int");

                    b.HasKey("Personel_Role_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Rol_Id");

                    b.ToTable("Personel_Roles");
                });

            modelBuilder.Entity("entity.Concrate.Puanlama", b =>
                {
                    b.Property<int>("Puanlama_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Puanlama_Id"));

                    b.Property<string>("Kategori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Puan")
                        .HasColumnType("float");

                    b.HasKey("Puanlama_Id");

                    b.ToTable("Puanlamas");
                });

            modelBuilder.Entity("entity.Concrate.Rol", b =>
                {
                    b.Property<int>("Rol_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Rol_Id"));

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rol_Id");

                    b.ToTable("Rols");
                });

            modelBuilder.Entity("entity.Concrate.TezYoneticiligi", b =>
                {
                    b.Property<int>("TezYoneticiligi_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TezYoneticiligi_Id"));

                    b.Property<string>("Enstutu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Katsayi_Id")
                        .HasColumnType("int");

                    b.Property<int>("Personel_Id")
                        .HasColumnType("int");

                    b.Property<double?>("Puan")
                        .HasColumnType("float");

                    b.Property<int>("Puanlama_Id")
                        .HasColumnType("int");

                    b.Property<int?>("Yil")
                        .HasColumnType("int");

                    b.HasKey("TezYoneticiligi_Id");

                    b.HasIndex("Katsayi_Id");

                    b.HasIndex("Personel_Id");

                    b.HasIndex("Puanlama_Id");

                    b.ToTable("TezYoneticiligis");
                });

            modelBuilder.Entity("entity.Concrate.Unvan", b =>
                {
                    b.Property<int>("Unvan_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Unvan_Id"));

                    b.Property<string>("Isim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Unvan_Id");

                    b.ToTable("Unvans");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("entity.Concrate.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("entity.Concrate.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("entity.Concrate.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("entity.Concrate.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("entity.Concrate.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("entity.Concrate.ArastirmaProjesi", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("ArastirmaProjesis")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("ArastirmaProjesis")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("ArastirmaProjesis")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Atif", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("Atifs")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("Atifs")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("Atifs")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Basvuru", b =>
                {
                    b.HasOne("entity.Concrate.Ilan", null)
                        .WithMany("Basvurus")
                        .HasForeignKey("Ilan_Id");

                    b.HasOne("entity.Concrate.Personel", null)
                        .WithMany("Basvurus")
                        .HasForeignKey("Personel_Id");
                });

            modelBuilder.Entity("entity.Concrate.Belge", b =>
                {
                    b.HasOne("entity.Concrate.Basvuru", "Basvuru")
                        .WithMany("Belges")
                        .HasForeignKey("Basvuru_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basvuru");
                });

            modelBuilder.Entity("entity.Concrate.BilimselToplanti", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("BilimselToplantis")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("BilimselToplantis")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("BilimselToplantis")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Editorluk", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("Editorluks")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("Editorluks")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("Editorluks")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.EoFaaliyetleri", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("EoFaaliyetleris")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("EoFaaliyetleris")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("EoFaaliyetleris")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Gorev", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("Gorevs")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("Gorevs")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("Gorevs")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Kitap", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("Kitaps")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("Kitaps")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("Kitaps")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Konservatuvar", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("Konservatuvars")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("Konservatuvars")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("Konservatuvars")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Makale", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("Makales")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("Makales")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("Makales")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Odul", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("Oduls")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("Oduls")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("Oduls")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Patent", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("Patents")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("Patents")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("Patents")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Personel", b =>
                {
                    b.HasOne("entity.Concrate.Unvan", "Unvan")
                        .WithMany("Personels")
                        .HasForeignKey("Unvan_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unvan");
                });

            modelBuilder.Entity("entity.Concrate.Personel_Role", b =>
                {
                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("Personel_Roles")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Rol", "Rol")
                        .WithMany("Personel_Roles")
                        .HasForeignKey("Rol_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personel");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("entity.Concrate.TezYoneticiligi", b =>
                {
                    b.HasOne("entity.Concrate.Katsayi", "Katsayi")
                        .WithMany("TezYoneticiligis")
                        .HasForeignKey("Katsayi_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Personel", "Personel")
                        .WithMany("TezYoneticiligis")
                        .HasForeignKey("Personel_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("entity.Concrate.Puanlama", "Puanlama")
                        .WithMany("TezYoneticiligis")
                        .HasForeignKey("Puanlama_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Katsayi");

                    b.Navigation("Personel");

                    b.Navigation("Puanlama");
                });

            modelBuilder.Entity("entity.Concrate.Basvuru", b =>
                {
                    b.Navigation("Belges");
                });

            modelBuilder.Entity("entity.Concrate.Ilan", b =>
                {
                    b.Navigation("Basvurus");
                });

            modelBuilder.Entity("entity.Concrate.Katsayi", b =>
                {
                    b.Navigation("ArastirmaProjesis");

                    b.Navigation("Atifs");

                    b.Navigation("BilimselToplantis");

                    b.Navigation("Editorluks");

                    b.Navigation("EoFaaliyetleris");

                    b.Navigation("Gorevs");

                    b.Navigation("Kitaps");

                    b.Navigation("Konservatuvars");

                    b.Navigation("Makales");

                    b.Navigation("Oduls");

                    b.Navigation("Patents");

                    b.Navigation("TezYoneticiligis");
                });

            modelBuilder.Entity("entity.Concrate.Personel", b =>
                {
                    b.Navigation("ArastirmaProjesis");

                    b.Navigation("Atifs");

                    b.Navigation("Basvurus");

                    b.Navigation("BilimselToplantis");

                    b.Navigation("Editorluks");

                    b.Navigation("EoFaaliyetleris");

                    b.Navigation("Gorevs");

                    b.Navigation("Kitaps");

                    b.Navigation("Konservatuvars");

                    b.Navigation("Makales");

                    b.Navigation("Oduls");

                    b.Navigation("Patents");

                    b.Navigation("Personel_Roles");

                    b.Navigation("TezYoneticiligis");
                });

            modelBuilder.Entity("entity.Concrate.Puanlama", b =>
                {
                    b.Navigation("ArastirmaProjesis");

                    b.Navigation("Atifs");

                    b.Navigation("BilimselToplantis");

                    b.Navigation("Editorluks");

                    b.Navigation("EoFaaliyetleris");

                    b.Navigation("Gorevs");

                    b.Navigation("Kitaps");

                    b.Navigation("Konservatuvars");

                    b.Navigation("Makales");

                    b.Navigation("Oduls");

                    b.Navigation("Patents");

                    b.Navigation("TezYoneticiligis");
                });

            modelBuilder.Entity("entity.Concrate.Rol", b =>
                {
                    b.Navigation("Personel_Roles");
                });

            modelBuilder.Entity("entity.Concrate.Unvan", b =>
                {
                    b.Navigation("Personels");
                });
#pragma warning restore 612, 618
        }
    }
}
